Updating MtHaml Lexer.php to support twig 1.27+
arnaud-lb/Silex-MtHaml pull request #1
Opened 2016-12-02 07:14 UTC by Boorj

Also the final part should look like this:

```php
$source = new Twig_Source($code, $filename);
return $this->lexer->tokenize($source);
```
Because, of deprecation [here](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Lexer.php#L81)

2016-12-03 17:23 UTC, arnaud-lb requested changes

2016-12-03 17:23 UTC, arnaud-lb commented on src/SilexMtHaml/Lexer.php
> +                $filename = $code->getName();
Could you add curly braces around this ? This is required to conform to PSR-2 coding style :)

2016-12-08 06:26 UTC, Boorj commented on src/SilexMtHaml/Lexer.php
> +                $filename = $code->getName();
yeah, sure!

2016-12-08 06:32 UTC, Boorj commented
@arnaud-lb Done! And, by the way, **Нuge** thank you for mthaml. Using that for several years, the keystone in my website projects. Now using Bolt.cms (based on silex), integrated mthaml into that cms.
Mthaml is lacking full syntax highlighting support in phpstorm, but that's the problem of phpstorm ;) :bowtie:

2016-12-08 06:38 UTC, Boorj commented
@arnaud-lb by the way, in twig 2.0 string `$code` will be removed and it's currently deprecated. So, maybe, we can make a separate branch and return `Twig_source` instance instead of `$code, $filename`. Twig_source also contains path field, as i remember..

2016-12-08 10:48 UTC, arnaud-lb commented
I agree, ideally we should return a Twig_Source when we get a Twig_Source. Do you want to make the change ?

2016-12-13 12:09 UTC, Boorj commented
Done, now it's conditional.

2016-12-13 18:38 UTC, arnaud-lb approved these changes

2016-12-13 18:38 UTC, merged

2016-12-13 18:38 UTC, arnaud-lb commented
Thanks!